### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Gian-Paolo-Paredes**
I am unsure how to fix these remaining merge conflicts, for the most part its just different numbers. Are these ok enough to be too much trouble?

### CODE REVIEW

**Comment by AlexSm9** [comment]
I merged it but there are still some problems, most notably: the fire animation at the title screen does not exist because the asset for it was not found. There arrows which are meant to point to water, but point to the ground instead.

**Comment by Gian-Paolo-Paredes** [comment]
Ok, the assets must not have gone all the way through then, i will upload
the tile atlas and josm in the drive then since its just 2 assets, for the
arrow all you have to do is - 60 on the y axis in the object i think.

**Comment by AlexSm9** [comment]
> \- 60 on the y axis in the object i think.

Not sure what you mean by this, you'll need to point me to a specific line of code if you'd like me to fix it.

**Comment by Gian-Paolo-Paredes** [comment]
Tomorrow it is, the tile atlas for the animations are in the drive with the
stylesheet too. It should make the animation work.

**Comment by AlexSm9** [comment]
Fixed the animation, check out the latest develop commit if you want to check what it looks like.

**Comment by Gian-Paolo-Paredes** [comment]
What do u think of the animation? Caleb is going to redo the title logo to
go on top later.

**Pull request merged**
